In [6]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [7]:
df = pd.read_csv('homeprices.csv')
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [8]:
model = LinearRegression()
model.fit(df[['area']], df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [9]:
model.coef_

array([135.78767123])

In [10]:
model.intercept_

180616.43835616432

In [11]:
model.predict([[5000]])

array([859554.79452055])

# Using pickle

In [1]:
import pickle

In [10]:
with open('model_pickle_me', 'wb') as file:
    pickle.dump(model, file)

In [2]:
with open('model_pickle_me', 'rb') as file:
    new_model = pickle.load(file)

In [3]:
new_model.coef_

array([135.78767123])

In [4]:
new_model.intercept_

180616.43835616432

In [5]:
new_model.predict([[5000]])

array([859554.79452055])

# Using joblib (use when large numpy array is there)

In [1]:
from sklearn.externals import joblib

c:\users\yash meshram\appdata\local\programs\python\python37\lib\site-packages\sklearn\externals\joblib\__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


In [13]:
joblib.dump(model, 'model_joblib_me')

['model_joblib_me']

In [2]:
model_joblib = joblib.load('model_joblib_me')

In [3]:
model_joblib.coef_

array([135.78767123])

In [4]:
model_joblib.intercept_

180616.43835616432

In [5]:
model_joblib.predict([[5000]])

array([859554.79452055])